### ISSUE TITLE
Setting `channel: @username` does not seem to work

### ISSUE THREAD

**Issue by AJamesPhillips** [pcolby/post-to-slack#3]
Thanks for this great repo & tool 🙂

I have set the `channel: ` to my username but do not receive a message.  I have tried upper and lower case.  The logs show:

```
Run pcolby/post-to-slack@v1
  with:
    url: ***
    text: Testing
    channel: @AJP
    username: GitHub Actions
    iconUrl: https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/png/github.png
    dryRun: false
```

And it does not error but no message appears.  Perhaps this a configuration option in Slack which silently drops messages to users from programmatic sources?  It works fine when `channel` is set to a channel like '#dev'
